name: Publish Plugin to JetBrains Marketplace

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
        timeout-minutes: 5
        continue-on-error: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build plugin
        run: |
          ./gradlew buildPlugin --stacktrace

      - name: Determine Marketplace Channel
        id: channel
        shell: bash
        run: |
          # Default channel is "default"
          CHANNEL="default"
          # If this is a GitHub Release event and it's marked as prerelease, use "eap"
          if [[ "${{ github.event_name }}" == "release" ]]; then
            if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
              CHANNEL="eap"
            fi
          fi
          # If tag contains -eap or -beta or -rc, also use eap channel
          if [[ "${GITHUB_REF##*/}" =~ -eap|-beta|-rc ]]; then
            CHANNEL="eap"
          fi
          echo "channel=$CHANNEL" >> "$GITHUB_OUTPUT"

      - name: Publish to JetBrains Marketplace
        if: env.MARKETPLACE_TOKEN != ''
        env:
          MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
          MARKETPLACE_CHANNEL: ${{ steps.channel.outputs.channel }}
        run: |
          ./gradlew publishPlugin --stacktrace

      - name: Skip publish (token not configured)
        if: env.MARKETPLACE_TOKEN == ''
        run: echo "MARKETPLACE_TOKEN is not configured; build succeeded but publishing is skipped."
